blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_citizen_web_app_id
     ***REMOVED***
  referencedataservice:
    servicehost:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
  applicationmanagementservice:
    servicehost:
      host: localhost
      port: 8680
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/application-management-service/1.0.0

logging:
  level:
    root: ${APP_LOGGING_LEVEL:-INFO}

    uk.gov.dft.bluebadge.webapp.citizen: ${APP_LOGGING_LEVEL:-DEBUG}

management:
  server:
    port: 8781
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
  profiles:
    active: dev
      # include: static/css/**,static/js/**

server:
  port: 8780
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 30

security:
  oauth2:
    client:
      client-id: ${blue-badge.auth-server.client-id}
       ***REMOVED***
      access-token-uri: ${blue-badge.auth-server.url}/oauth/token
      auto-approve-scopes: '.*'
      authorized-grant-types: client_credentials
