blue-badge:
  auth-server:
    url: http://localhost:8380/bb_auth
    client-id: bb_citizen_web_app_id
     ***REMOVED***
  referencedataservice:
    servicehost:
      host: localhost
      port: 8580
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/reference-data-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json
  applicationmanagementservice:
    servicehost:
      host: localhost
      port: 8680
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/application-management-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json
  paymentservice:
    servicehost:
      host: localhost
      port: 8980
      scheme: http
      connectiontimeout: 6000
      requesttimeout: 6000
      contextpath: /uk-gov-dft/payment-service/1.0.0
      versionaccept: application/vnd.bluebadge-api.v1+json
  env: ${bb_env:dev}
  defaultDifferentServiceSignpostUrl: https://bluebadge.direct.gov.uk/bluebadge/why-are-you-here

logging:
  level:
    root: ${APP_LOGGING_LEVEL:INFO}
    uk.gov.dft.bluebadge.webapp.citizen: ${APP_LOGGING_LEVEL:DEBUG}
    org.springframework: INFO

management:
  server:
    port: 8781
    servlet:
      context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 150MB
  session:
    store-type: redis
    redis:
      namespace: spring:session:citizen
  redis:
    host: localhost
  devtools:
    restart:
      additional-exclude: sass/**,js/**
      poll-interval: 10
      quiet-period: 5
  resources:
    chain:
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /js/**,/css/**

server:
  port: 8780
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    session:
      timeout: 60m

security:
  oauth2:
    client:
      client-id: ${blue-badge.auth-server.client-id}
       ***REMOVED***
      access-token-uri: ${blue-badge.auth-server.url}/oauth/token
      auto-approve-scopes: '.*'
      authorized-grant-types: client_credentials

# Google Analytics Code
GACode:  ${GACODE:UA-124760983-5}

amazon:
  s3bucket: uk-gov-dft-dev-applications-temp
  signed-url-duration-ms: 60000
