blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  referencedataservice:
    servicehost:
      host: referencedata-service
  applicationmanagementservice:
    servicehost:
      host: applications-service

spring:
  redis:
    host: redis

amazon:
  s3bucket: ${bb_application_tmp_bucket:uk-gov-dft-ci-applications-temp}
