blue-badge:
  auth-server:
    url: http://authorisation-service:8380/bb_auth
  referencedataservice:
    servicehost:
      host: referencedata-service
  applicationmanagementservice:
    servicehost:
      host: applications-service
  paymentservice:
    servicehost:
      host: payment-service

spring:
  main:
    banner-mode: "off"
  redis:
    host: redis
  resources:
    static-locations: classpath:/static/
    cache:
      cachecontrol:
        no-store: false
        max-age: 315360000
amazon:
  s3bucket: ${bb_application_tmp_bucket:uk-gov-dft-dev-applications-temp}
